spring.application.name=gatherly
spring.datasource.url=jdbc:mysql://localhost:3306/gatherly
spring.datasource.username=root
spring.datasource.password=vishaliphone
spring.jpa.show-sql=true

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

