spring:
  application:
    name: gatherly

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  datasource:
    url: jdbc:mysql://localhost:3306/gatherly
    username: root
    password: vishaliphone

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  logging:
    level:
      liquibase: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: vdas53073@gmail.com
    password: jbny iwrk ezdt ljvx  # not normal password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    remainder:
      subject: Event Remainder
      message: